plugins:
  - jasmine
env:
  commonjs: true
  es6: true
  node: true
  jasmine: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {}
